#version: "2"
version: "2"
services:


  web:
    image: nginx:alpine
    ports:
      - "8081:80"
    #depends_on:
    #  - php
    #links:
    #  - php
    restart: always
    volumes:
      - /home/devops/nginx/app.conf:/etc/nginx/conf.d/app.conf
      - /home/sites/aws.dev.br/public:/var/www/html



volumes:
  nginx:
  public:
 
  