version: "2"

services:



  wp:
    image: wordpress:latest
    ports:
      - "$PORT:80"
      - "4433:443"
    depends_on:
      - mysqlserver
    links:
      - mysqlserver
    environment:
      DOMINIO: ${DOMINIO}
      WORDPRESS_DB_HOST: mysqlserver
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: database
    restart: always
    volumes:
      - /home/sites/${DOMINIO}/public:/var/www/html
      - ./conf/php.ini:/usr/local/etc/php/php.ini
      - ./conf/php.ini:/$PHP_INI_DIR/conf.d/php.ini
 

  mysqlserver:
    image: mysql:5.7
    #command: [ "--default-authentication-plugin=mysql_native_password" ]
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - /home/sites/${DOMINIO}/db_dados:/var/lib/mysql


  phpmyadmin:
    image: phpmyadmin:apache
    restart: always
    ports:
      - "8082:80"
    environment:
      - PMA_ARBITRARY=1
    links:
      - mysqlserver

 
  