#version: "2"
version: "2"

services:


  web:
    image: nginx:alpine
    ports:
      - "8081:80"
    networks:
      - wp01
    depends_on:
      - php
    links:
      - php
    restart: always
    volumes:
      - /home/beta/app.conf:/etc/nginx/conf.d/app.conf
      - /home/beta/public:/var/www/html


  php:
    image: php:fpm
    networks:
      - wp01
    restart: always
    volumes:
      - /home/beta/public:/var/www/html
      - /home/beta/php.ini:/usr/local/etc/php/php.ini 
    

  mysqlserver:
    image: mysql:5.7
    command: [ "--default-authentication-plugin=mysql_native_password" ]
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress 
      MYSQL_DATABASE: wordpress 
      MYSQL_USER: wordpress 
      MYSQL_PASSWORD: wordpress
    volumes:
      - /home/sites/${DOMINIO}/db_dados:/var/lib/mysql


networks:
  wp01:
  