version: "3.9"

services:

  wp:
    image: wordpress
    ports:
      - "8081:80"
    depends_on:
      - mysqlserver
    links:
      - mysqlserver
    environment:
      DOMINIO: ${DOMINIO}
      WORDPRESS_DB_HOST: mysqlserver
      WORDPRESS_DB_USER: ${DBUSER}
      WORDPRESS_DB_PASSWORD: ${DBPASS}
      WORDPRESS_DB_NAME: ${DBNAME}
    restart: always
    volumes:
      - /home/sites/${DOMINIO}/public:/var/www/html
 

  mysqlserver:
    image: mysql:5.7
    command: [ "--default-authentication-plugin=mysql_native_password" ]
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DBPASSROOT}
      MYSQL_DATABASE: ${DBNAME}
      MYSQL_USER: ${DBUSER}
      MYSQL_PASSWORD: ${DBPASS}
    volumes:
      - /home/sites/${DOMINIO}/db_dados:/var/lib/mysql


  phpmyadmin:
    image: phpmyadmin:apache
    restart: always
    ports:
      - "8082:80"
    environment:
      - PMA_ARBITRARY=1
    links:
      - mysqlserver

 
  