#version: "2"
version: "2"

services:


  web:
    image: nginx:alpine
    ports:
      - "8081:80"
    depends_on:
      - php
    links:
      - php
    restart: always
    volumes:
      - /home/beta/app.conf:/etc/nginx/conf.d/app.conf
      - /home/beta/public:/var/www/html


  php:
    image: php:fpm
    restart: always
    volumes:
      - /home/beta/public:/var/www/html
      - /home/beta/php.ini:/usr/local/etc/php/php.ini 
    


networks:
  wp01:
  