version: "3.9"
services:

  web:
    image: nginx:alpine
    ports:
      - "8081:80"
    depends_on:
      - wordpress
    links:
      - wordpress
    restart: always
    volumes:
      - ./conf/app.conf:/etc/nginx/conf.d/app.conf
      - ./app:/var/www/html
      
  wordpress:
    image: wordpress:php7.4-fpm
    ports:
      - "9000:9000"
    restart: always
    volumes:
      - ./app:/var/www/html
      - ./conf/php.ini:/usr/local/etc/php/php.ini
    environment:
      DOMINIO: ${DOMINIO}
      WORDPRESS_DB_HOST: ${DOMINIO}
      WORDPRESS_DB_USER: ${DBUSER}
      WORDPRESS_DB_PASSWORD: ${DBPASS}
      WORDPRESS_DB_NAME: ${DBNAME}
    links:
      - mysqlserver
      - redis 
      
  mysqlserver:
    image: mysql:5.7
    command: [ "--default-authentication-plugin=mysql_native_password" ]
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DBPASSROOT}
      MYSQL_DATABASE: ${DBNAME}
      MYSQL_USER: ${DBUSER}
      MYSQL_PASSWORD: ${DBPASS}
    volumes:
      - ./db_dados:/var/lib/mysql

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always

  phpmyadmin:
    image: phpmyadmin:apache
    restart: always
    ports:
      - "8082:80"
    environment:
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=500M
    links:
      - mysqlserver
    

volumes:
  app:
  conf:
  db_dados:
 
  